version: '3'
services:
  nginx:
    image: nginx:1.20.2
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/code/www:/usr/share/nginx/html
      - ~/code/webserver/nginx/conf.d:/etc/nginx/conf.d
      - ~/code/webserver/nginx/logs:/var/log/nginx
    depends_on:
      - php8

  php8:
    build: ./php/php8
    container_name: php8
    volumes:
      - ~/code/www:/var/www/html
      - ~/code/webserver/php/php8/conf:/usr/local/etc/php
    links:
      - mysql
      - mailhog
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/code/webserver/mysql/conf:/etc/mysql
      - ~/code/webserver/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--default-authentication-plugin=mysql_native_password'
      ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    links:
      - mysql

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
